context("Summary_Categorical")
#####

df <- mtcars %>% group_by(am) %>% select(gear)
df2 <- mtcars %>% group_by(am) %>% select(gear, carb)
df3 <- mtcars %>% select(gear)
test_that("count_percentage works (when adjusting N and round.N)", {
  expect_result_original <- data.frame(x = c(3,4,5),
                                       freq = c(15L, 12L, 5L),
                                       percentage = c(0.469, 0.375, 0.156))
  expect_result_N_on <- data.frame(x = c(3,4,5), N = c(32L, 32L, 32L), freq = c(15L, 12L, 5L), percentage = c(0.469, 0.375, 0.156))
  expect_result_nrd_2 <- data.frame(x = c(3,4,5), N = c(32L, 32L, 32L), freq = c(15L, 12L, 5L), percentage = c(0.47, 0.38, 0.16))

  expect_equal(count_percentage(df$gear), expected = expect_result_original)
  expect_equal(count_percentage(df$gear, n = T), expected = expect_result_N_on)
  expect_equal(count_percentage(df$gear, round.N = 2), expected = select(expect_result_nrd_2, - N))
  expect_equal(count_percentage(df$gear, n = T, round.N = 2), expected = expect_result_nrd_2)
  })

test_that("count_percentage_ can calculate based on grouping information generated by dplyr", {
  expected_result_original <- data.frame(am = c(0, 0, 1, 1), gear = c(3,4,4,5), freq = c(15L,4L,8L,5L), percentage = c(0.789, 0.211, 0.615, 0.385))
  attributes(expected_result_original)$class = c("grouped_df", "tbl_df", "tbl", "data.frame")
  attributes(expected_result_original)$vars = list(as.symbol("am"))
  attributes(expected_result_original)$drop = c(TRUE)
  attributes(expected_result_original)$indices = list(c(0,1), c(2,3))
  attributes(expected_result_original)$group_sizes = c(2,2)
  attributes(expected_result_original)$biggest_group_size = c(2)
  attributes(expected_result_original)$labels = structure(list(am = c(0,1)), vars = attributes(expected_result_original)$vars)

  expect_equivalent(count_percentage_(df), expected = expected_result_original)
  expect_equal(attributes(count_percentage_(df))$class, expected = attributes(expected_result_original)$class)
  expect_equal(attributes(count_percentage_(df))$vars, expected = attributes(expected_result_original)$vars)
})

test_that("count_percentage_ can also analyze 2 or more variables", {
  expect_equal(dim(count_percentage_(df2)), expected = c(13,5))
})

test_that("count_percentage_ can also analyze 2 or more variables", {
  expect_equal(dim(count_percentage_(df2)), expected = c(13,5))
})

test_that("ez_summarise_categorical can work without grouping data", {
  expect_equal(names(ez_summarise_categorical(df3)), expected = c("x", "freq", "percentage"))
  expect_equal(names(ez_summarise_categorical(df3, n=T)), expected = c("x", "N", "freq", "percentage"))
  expect_equal(ez_summarise_categorical(df3)[2], expected = structure(list(freq = c(15L, 12L,5L)), class = c("tbl_df", "data.frame"), row.names = 1:3))
  expect_equal(ez_summarise_categorical(df3, n=T)[2:3], expected = structure(list(N=c(32L, 32L, 32L), freq = c(15L, 12L,5L)), class = c("tbl_df", "data.frame"), row.names = 1:3))
})

test_that("ez_summarise_categorical can rename the variables for data with grouping info", {
  expect_equal(names(ez_summarise_categorical(df2))[2], expected = c("x"))
  expect_equal(names(ez_summarise_categorical(df2, n=T))[2:3], expected = c("x", "N"))
  expect_equivalent(as.character(ez_summarise_categorical(df2)[2, 2]), expected = c("gear_4"))
  expect_equivalent(as.character(ez_summarise_categorical(df2, n=T)[2, 2:3]), expected = c("gear_4", "19"))
})

test_that("ez_summarise_categorical can export n.group and n.var", {
  expect_equal(attributes(ez_summarise_categorical(df))$n.group, expected = 1)
  expect_equal(attributes(ez_summarise_categorical(df))$n.var, expected = 1)
  expect_equal(attributes(ez_summarise_categorical(df2))$n.group, expected = 1)
  expect_equal(attributes(ez_summarise_categorical(df2))$n.var, expected = 2)
})
